# Generated by Django 4.2.7 on 2024-01-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(1, "男"), (2, "女")], default="1", verbose_name="性别"
            ),
        ),
    ]
