# Generated by Django 4.2.7 on 2024-01-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_teacher_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="age",
            field=models.IntegerField(default=0, verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="birthday",
            field=models.DateField(default="无", verbose_name="出生日期"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="education",
            field=models.SmallIntegerField(
                choices=[(1, "大专"), (2, "本科"), (3, "研究生"), (4, "博士")],
                default="1",
                verbose_name="学历",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="grade",
            field=models.SmallIntegerField(
                choices=[
                    (1, "小学一年级"),
                    (2, "小学二年级"),
                    (3, "小学三年级"),
                    (4, "小学四年级"),
                    (5, "小学五年级"),
                    (6, "小学六年级"),
                    (7, "初一"),
                    (8, "初二"),
                    (9, "初三"),
                    (10, "高一"),
                    (11, "高二"),
                    (12, "高三"),
                    (13, "大学生"),
                ],
                default="1",
                verbose_name="可授年级",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="graduate",
            field=models.CharField(default="无", max_length=100, verbose_name="毕业院校"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="major",
            field=models.CharField(default="无", max_length=64, verbose_name="所学专业"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="method",
            field=models.SmallIntegerField(
                choices=[
                    (1, "一对一家教上门"),
                    (2, "一对多家教上门"),
                    (3, "机构小班授课"),
                    (4, "机构大班授课"),
                    (5, "远程网络授课"),
                ],
                default="1",
                verbose_name="授课方式",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="region",
            field=models.CharField(default="无", max_length=64, verbose_name="所在区域"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="regions",
            field=models.CharField(default="无", max_length=64, verbose_name="可授课区域"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.SmallIntegerField(
                choices=[
                    (1, "语文"),
                    (2, "数学"),
                    (3, "英语"),
                    (4, "物理"),
                    (5, "化学"),
                    (6, "政治"),
                    (7, "历史"),
                    (8, "地理"),
                    (9, "生物"),
                    (10, "考研课程"),
                ],
                default="1",
                verbose_name="教授科目",
            ),
        ),
    ]
